// File: input_user_model.dart (Pastikan ini adalah isi file Anda)

import 'package:cloud_firestore/cloud_firestore.dart';

/// [QuestionAnswer] merepresentasikan data satu jawaban untuk satu pertanyaan tertentu.
/// 
/// Digunakan untuk menyimpan hasil input responden beserta metadata pertanyaan aslinya
/// seperti teks pertanyaan dan tipenya.
class QuestionAnswer {
  /// ID unik pertanyaan yang dirujuk.
  final String questionId;
  /// Teks pertanyaan saat data ini diisi.
  final String questionText;
  /// Nilai jawaban dari pengguna (bisa berupa String, num, List, atau Map).
  dynamic answer;
  /// Tipe pertanyaan (text, number, multipleChoice, dll).
  final String questionType;

  QuestionAnswer({
    required this.questionId,
    required this.questionText,
    this.answer,
    required this.questionType,
  });

  /// Mengonversi objek [QuestionAnswer] ke format Map untuk Firestore.
  Map<String, dynamic> toMap() {
    return {
      'questionId': questionId,
      'questionText': questionText,
      'answer': answer,
      'questionType': questionType,
    };
  }

  /// Membuat instance [QuestionAnswer] dari format Map.
  factory QuestionAnswer.fromMap(Map<String, dynamic> map) {
    return QuestionAnswer(
      questionId: map['questionId'] ?? '',
      questionText: map['questionText'] ?? '',
      answer: map['answer'],
      questionType: map['questionType'] ?? '',
    );
  }
}

/// [FormSubmission] merepresentasikan satu set lengkap jawaban dari pengisian sebuah formulir.
/// 
/// Model ini menampung seluruh informasi hasil pendataan di lapangan, termasuk metadata
/// petugas, wilayah (RT/RW/Desa), koordinat lokasi, foto, dan hasil rekapitulasi otomatis.
class FormSubmission {
  /// ID dokumen unik di Firestore (bisa null jika data baru).
  String? id;
  /// ID formulir yang diisi.
  final String formId;
  /// Judul formulir saat diisi.
  final String formTitle;
  /// UID petugas yang mengisi.
  final String userId;
  /// Nama petugas yang mengisi.
  final String userName;
  /// Periode pendataan aktif (Format: yyyy-MM).
  final String? period; 
  /// ID Desa lokasi pendataan.
  final String? villageId;   
  /// Nama Desa lokasi pendataan.
  final String? villageName; 
  /// Nomor RT lokasi pendataan.
  final String? rt;          
  /// Nomor RW lokasi pendataan.
  final String? rw;          
  /// Waktu data ini dikirimkan.
  final Timestamp submittedAt;
  /// Daftar seluruh jawaban pertanyaan.
  final List<QuestionAnswer> answers;
  
  /// Koordinat lokasi GPS dalam format [GeoPoint].
  GeoPoint? location;
  /// Nilai Latitude lokasi.
  double? latitude; 
  /// Nilai Longitude lokasi.
  double? longitude; 
  /// Alamat lengkap hasil reverse-geocoding koordinat.
  String? locationAddress; 
  /// Tingkat akurasi GPS dalam meter.
  double? locationAccuracy; 
  
  /// URL foto utama yang diunggah.
  String? imageUrl; 
  /// Daftar URL seluruh foto yang diunggah (jika lebih dari satu).
  List<String>? imageUrls; 
  
  /// Waktu terakhir data ini diperbarui.
  Timestamp? updatedAt;
  /// Waktu pertama kali data isian dibuat.
  Timestamp? createdAt; 

  /// Status pengiriman data ("draft", "submitted", "locked").
  final String status; 
  /// Menandakan data ini sudah terkunci dan tidak bisa diedit.
  final bool isLocked;
  /// Menandakan data ini hasil generate otomatis (Auto Duplicate).
  final bool isAutoGenerated;
  /// Periode asal data jika ini merupakan hasil duplikasi otomatis.
  final String? duplicatedFromPeriod;

  /// Nama Kepala Rumah Tangga hasil ekstraksi cerdas dari isian.
  final String? namaKepalaRumahTangga;
  /// Judul tampilan ringkas untuk daftar di dashboard.
  final String? displayTitle;
  /// Deskripsi tampilan ringkas untuk daftar di dashboard.
  final String? displayDescription;
  /// Hasil rekapitulasi kelompok usia otomatis untuk isian ini.
  final Map<String, dynamic>? computedSummary;

  FormSubmission({
    this.id,
    required this.formId,
    required this.formTitle,
    required this.userId,
    required this.userName,
    this.period,
    this.villageId,
    this.villageName,
    this.rt,
    this.rw,
    required this.submittedAt,
    required this.answers,
    this.location,
    this.latitude,
    this.longitude,
    this.locationAddress,
    this.locationAccuracy,
    this.imageUrl,
    this.imageUrls,
    this.updatedAt,
    this.createdAt,
    this.status = "submitted",
    this.isLocked = false,
    this.isAutoGenerated = false,
    this.duplicatedFromPeriod,
    this.namaKepalaRumahTangga,
    this.displayTitle,
    this.displayDescription,
    this.computedSummary,
  });

  /// Mengonversi objek [FormSubmission] ke format Map yang siap disimpan di Firestore.
  Map<String, dynamic> toFirestore() {
    return {
      'formId': formId,
      'formTitle': formTitle,
      'userId': userId,
      'userName': userName,
      if (period != null) 'period': period,
      if (villageId != null) 'villageId': villageId,
      if (villageName != null) 'villageName': villageName,
      if (rt != null) 'rt': rt,
      if (rw != null) 'rw': rw,
      'submittedAt': submittedAt,
      'answers': answers.map((answer) => answer.toMap()).toList(),
      if (location != null) 'location': location,
      if (latitude != null) 'latitude': latitude,
      if (longitude != null) 'longitude': longitude,
      if (locationAddress != null) 'locationAddress': locationAddress,
      if (locationAccuracy != null) 'locationAccuracy': locationAccuracy,
      if (imageUrl != null) 'imageUrl': imageUrl,
      if (imageUrls != null) 'imageUrls': imageUrls,
      if (updatedAt != null) 'updatedAt': updatedAt,
      if (createdAt != null) 'createdAt': createdAt,
      'status': status,
      'isLocked': isLocked,
      'isAutoGenerated': isAutoGenerated,
      if (duplicatedFromPeriod != null) 'duplicatedFromPeriod': duplicatedFromPeriod,
      if (displayTitle != null) 'displayTitle': displayTitle,
      if (displayDescription != null) 'displayDescription': displayDescription,
      if (computedSummary != null) 'computedSummary': computedSummary,
    };
  }

  /// Factory constructor untuk memetakan dokumen Firestore ke objek [FormSubmission].
  factory FormSubmission.fromFirestore(DocumentSnapshot<Map<String, dynamic>> doc) {
    return FormSubmission.fromMap(doc.data()!, doc.id);
  }

  /// Memetakan data mentah (Map) ke objek [FormSubmission] beserta ekstraksi otomatis nama KRT.
  factory FormSubmission.fromMap(Map<String, dynamic> data, String id) {
    final List<QuestionAnswer> allAnswers = (data['answers'] as List<dynamic>?)
            ?.map((answerMap) =>
                QuestionAnswer.fromMap(answerMap as Map<String, dynamic>))
            .toList() ??
        [];

    /// Helper internal untuk mengonversi data tanggal yang beragam ke format [Timestamp].
    Timestamp parseTimestamp(dynamic val) {
      if (val is Timestamp) return val;
      if (val is String) {
        try {
          return Timestamp.fromDate(DateTime.parse(val));
        } catch (_) {}
      }
      return Timestamp.now();
    }

    // --- LOGIKA UNTUK MENGISI namaKepalaRumahTangga ---
    String? extractedNamaKRT;
    const String targetQuestionIdForKRT = "106";

    try {
      final krtAnswerObject = allAnswers.firstWhere(
        (ans) =>
            ans.questionId == targetQuestionIdForKRT &&
            ans.answer != null &&
            ans.answer.toString().isNotEmpty,
      );
      extractedNamaKRT = krtAnswerObject.answer?.toString();
    } catch (e) {
      // Ignored
    }

    return FormSubmission(
      id: id,
      formId: data['formId'] ?? '',
      formTitle: data['formTitle'] ?? '',
      userId: data['userId'] ?? '',
      userName: data['userName'] ?? '',
      period: data['period'] as String?,
      villageId: data['villageId'] as String?,
      villageName: data['villageName'] as String?,
      rt: data['rt']?.toString(),
      rw: data['rw']?.toString(),
      submittedAt: parseTimestamp(data['submittedAt']),
      answers: allAnswers,
      location: data['location'] is GeoPoint ? data['location'] : null,
      latitude: (data['latitude'] as num?)?.toDouble(),
      longitude: (data['longitude'] as num?)?.toDouble(),
      locationAddress: data['locationAddress'] as String?,
      locationAccuracy: (data['locationAccuracy'] as num?)?.toDouble(),
      imageUrl: data['imageUrl'] as String?,
      imageUrls: (data['imageUrls'] as List<dynamic>?)
          ?.map((e) => e.toString())
          .toList(),
      updatedAt: data['updatedAt'] != null ? parseTimestamp(data['updatedAt']) : null,
      createdAt: data['createdAt'] != null ? parseTimestamp(data['createdAt']) : null,
      status: data['status'] as String? ?? "submitted",
      isLocked: data['isLocked'] as bool? ?? false,
      isAutoGenerated: data['isAutoGenerated'] as bool? ?? false,
      duplicatedFromPeriod: data['duplicatedFromPeriod'] as String?,
      namaKepalaRumahTangga: extractedNamaKRT,
      displayTitle: data['displayTitle'] as String?,
      displayDescription: data['displayDescription'] as String?,
      computedSummary: data['computedSummary'] as Map<String, dynamic>?,
    );
  }
}
