// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// [DefaultFirebaseOptions] menyediakan konfigurasi default [FirebaseOptions] 
/// untuk setiap platform yang didukung.
///
/// File ini secara otomatis dihasilkan oleh FlutterFire CLI dan berisi 
/// kunci API serta ID proyek yang diperlukan untuk menghubungkan aplikasi ke Firebase.
///
/// Contoh Penggunaan:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Mendapatkan konfigurasi [FirebaseOptions] berdasarkan platform saat ini (Android, Windows, dll).
  /// 
  /// Melemparkan [UnsupportedError] jika platform tidak didukung atau belum dikonfigurasi.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Konfigurasi Firebase untuk platform Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS2TK3v9uZX69bRz_mgAuEFN71U2-A5ZI',
    appId: '1:465498567418:android:18a88f02827c4e3da88f43',
    messagingSenderId: '465498567418',
    projectId: 'aplikasi-pendataan-desa',
    storageBucket: 'aplikasi-pendataan-desa.firebasestorage.app',
  );

  /// Konfigurasi Firebase untuk platform Windows.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS2TK3v9uZX69bRz_mgAuEFN71U2-A5ZI',
    appId: '1:465498567418:android:18a88f02827c4e3da88f43',
    messagingSenderId: '465498567418',
    projectId: 'aplikasi-pendataan-desa',
    storageBucket: 'aplikasi-pendataan-desa.firebasestorage.app',
  );

}
